Validate facility form fields
CDCgov/prime-simplereport pull request #1070
Opened 2021-03-11 22:01 UTC by nickscialli-usds

## Related Issue or Background Info

- Issue #917

## Changes Proposed

- Adds `yup` validation to facility fields
- Makes sure to validate the _correct_ fields
- Adds same phone number validation on frontend as is on backend (google)

## Additional Information

- This has more boilerplate than I'd ultimately like. I think we could use `react-hook-form` or another established form library on the front-end to make our forms consistent, have less boilerplate, and integrate relatively easily with a validation library like yup.

2021-03-11 22:38 UTC, nickscialli-usds commented
Would like to ignore the SonarCloud duplication failure, but will defer to reviewers on that one.

Basically, I think we have some tech debt in that we don't have a form management library to abstract away my home-rolled `validateField` and `clearError` functions. Therefore, I wrote them and then duplicated them across two components and SonarCloud is not a fan of that.

2021-03-11 22:57 UTC, timbest-usds approved these changes
I support ignoring the sonar duplication warning until we have a better method for managing forms

2021-03-11 22:57 UTC, timbest-usds commented on frontend/src/app/Settings/Facility/FacilityFormContainer.tsx
> -      county: ""
Thank you for cleaning this up

2021-03-11 23:08 UTC, timbest-usds requested changes

2021-03-11 23:08 UTC, timbest-usds commented on frontend/src/app/Settings/Facility/facilitySchema.ts
> +  street: yup.string().required("Ordering provider street is missing"),
The Ordering Providers address is not required. `street`, `state`, and `zipCode` should be optional

2021-03-11 23:21 UTC, timbest-usds commented on frontend/src/app/Settings/Facility/facilitySchema.ts
> +  street: yup.string().required("Ordering provider street is missing"),
....turns out nothing about the ordering provider is required

2021-03-12 14:43 UTC, timbest-usds approved these changes

2021-03-12 14:44 UTC, merged