[WIP] Create Organization site Admin on Organization Create
CDCgov/prime-simplereport pull request #1241
Opened 2021-04-02 22:37 UTC by ClydeDroid

## Related Issue or Background Info

- Resolves #1108 
- Resolves #931

## Changes Proposed

- Changes `createOrganization` mutation to include admin user info
- Adds a section for admin info to the create org form on the frontend
- I also changed `start.sh` to load env vars in `.env` so that I could get the form to submit (needed smarty streets token)

## Additional Information

- The linked issues originally called for accepting phone numbers for the admin, but @aliciabeckett-gov confirmed we don't need to store these, so I changed the accepted info to match the parameters from the `createUser` function in the `ApiUserService` (first middle last suffix and email)
- still working on tests, so this is WIP

## Screenshots / Demos
![image](https://user-images.githubusercontent.com/9121162/113459077-3c0b1180-93c9-11eb-95e9-ca69f4472839.png)

2021-04-07 21:52 UTC, timothybest-usds requested changes
I added a new component `Input`. Which is a strictly typed wrapper around `TextInput` that also stop the change event from leaking into the form logic. Added some code suggestions to use this new component in `FacilityAdmin.tsx`

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +import TextInput from "../../commonComponents/TextInput";
```suggestion
import Input from "../../commonComponents/Input";
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +  };
```suggestion
    const onChange = <K extends keyof FacilityAdmin>(field: K) => (
    value: FacilityAdmin[K]
  ) => {
    updateAdmin({ ...admin, [field]: value });
  };
  ```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="First name"
              field="firstName"
              formObject={admin}
              onChange={onChange}
              required
            />
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="First name"
              field="firstName"
              formObject={admin}
              onChange={onChange}
              required
            />
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="Middle name"
              field="middleName"
              formObject={admin}
              onChange={onChange}
              required
            />
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="Last name"
              field="lastName"
              formObject={admin}
              onChange={onChange}
              required
            />
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="Suffix"
              field="suffix"
              formObject={admin}
              onChange={onChange}
            />
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="Suffix"
              field="suffix"
              formObject={admin}
              onChange={onChange}
            />
```

2021-04-07 21:52 UTC, timothybest-usds commented on frontend/src/app/admin/Organization/FacilityAdmin.tsx
> +            />
```suggestion
            <Input
              label="Email"
              field="email"
              formObject={admin}
              onChange={onChange}
              required
            />
```

2021-04-08 00:21 UTC, maya commented
I'm not able to view this locally bc of the following typescript error:

```
/Users/mayabenari/Code/prime-simplereport/frontend/src/app/admin/Organization/FacilityAdmin.tsx
TypeScript error in /Users/mayabenari/Code/prime-simplereport/frontend/src/app/admin/Organization/FacilityAdmin.tsx(29,15):
Type '<K extends "email" | "firstName" | "middleName" | "lastName" | "suffix">(field: K) => (value: FacilityAdmin[K]) => void' is not assignable to type '(field: ReactText) => (value: string) => void'.
  Types of parameters 'field' and 'field' are incompatible.
    Type 'ReactText' is not assignable to type '"email" | "firstName" | "middleName" | "lastName" | "suffix"'.
      Type 'string' is not assignable to type '"email" | "firstName" | "middleName" | "lastName" | "suffix"'.  TS2322

    27 |               field="firstName"
    28 |               formObject={admin}
  > 29 |               onChange={onChange}
       |               ^
    30 |               required
    31 |             />
    32 |           </div>
```

If I'm just reviewing by the screenshot, then it's not up-to-date with the current single-column design added in #1243 and will need to be updated to follow.

2021-04-08 00:27 UTC, maya requested changes
See: https://github.com/CDCgov/prime-simplereport/pull/1241#issuecomment-815358145

Assuming this PR is changes to the facility form.

2021-04-08 15:18 UTC, ClydeDroid commented
@maya the typescript error was introduced by Tim's suggested changes, and I am working on resolving that.
The screenshot was taken before #1243 was merged. I have merged main to this branch since then, so the changes should be reflected, and you will be able to see that once I sort out the error.

2021-04-08 22:21 UTC, ClydeDroid commented
@maya Okay, changed the facility admin section to only have one column, does this look right?
![image](https://user-images.githubusercontent.com/9121162/114103397-ebd6f800-987d-11eb-8158-acd74ec1f481.png)

2021-04-08 22:29 UTC, maya commented
Better! Though do we know where org info is coming from? b/c that appears to be in 2 columns instead of 1 in the screenshot

2021-04-08 22:31 UTC, ClydeDroid commented
I can update that as well

2021-04-08 23:17 UTC, ClydeDroid commented
![image](https://user-images.githubusercontent.com/9121162/114107426-d6fe6280-9885-11eb-8ac5-6c9290aeaabd.png)

2021-04-09 17:50 UTC, maya approved these changes
Front end LGTM. Added a few minor type and spacing updates:
 
![localhost_3000_admin_create-organization_facility=1b2416eb-2c82-4e21-80ca-2f398365ce7b](https://user-images.githubusercontent.com/5249443/114220845-58ef9980-9921-11eb-9c63-6b2613a2d7c8.png)

2021-04-12 14:00 UTC, timothybest-usds approved these changes

2021-04-12 15:19 UTC, merged