Bob/2943 verify button inline
CDCgov/prime-simplereport pull request #3151
Opened 2021-12-22 02:10 UTC by fzhao99

## Related Issue or Background Info
Fixed integration test to account for new account verification flow made via #2943 by changing the selectors around. Also added in some extra unit tests for the PendingOrganizations component.

Got trigger happy and merged change before fixing the integration test. This PR fixes that!

The additional things we need to verify are commits after Dec 20, everything else was ok'ed in the other PR.

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

2021-12-22 18:14 UTC, nickclyde requested changes

2021-12-22 18:14 UTC, nickclyde commented on frontend/cypress/integration/01-organization_sign_up_spec.js
> +    cy.contains("Identity verified for Beach Camp", { timeout: 30000 });
Cool, thanks for updating :+1:

2021-12-22 18:14 UTC, nickclyde commented on package.json
> +    "eslint-plugin-cypress": "^2.12.1"
I don't think this needs to be added to the `package.json` in the root of the repo, it's already in `frontend/package.json`

2021-12-22 18:26 UTC, nickclyde commented on yarn.lock
> +eslint-plugin-cypress@^2.12.1:
Sorry, can you revert the changes to `yarn.lock` as well?

2021-12-22 18:30 UTC, nickclyde approved these changes
:+1:

2021-12-23 16:35 UTC, nathancrtr approved these changes

2021-12-23 17:40 UTC, merged