Alis/3049
CDCgov/prime-simplereport pull request #3734
Opened 2022-05-06 17:37 UTC by alismx

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Checklist for Primary Reviewer

- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke tested
- [ ] Any content updates (user-facing error messages, etc) have been approved by content team
- [ ] Any changes that might generate questions in the support inbox have been flagged to the support team
- [ ] GraphQL schema changes are backward compatible with older version of the front-end
- [ ] Changes comply with the SimpleReport Style Guide
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

----

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Checklist for Primary Reviewer

- [ ] Only database changes are included in this PR
- [ ] Any new tables or columns that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
- [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views (including re-granting permission to the no-PHI user if need be)
- [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] Rollback has been verifed locally and in a deployed environment

----

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?
 
## Checklist for Primary Reviewer

### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

----

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?
 
## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

## Checklist for Author and Reviewer

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

2022-05-10 16:08 UTC, zdeveloper requested changes
LGTM! with minor nitpicks

2022-05-10 16:08 UTC, zdeveloper commented on .github/workflows/test.yml
> -      - uses: actions/checkout@v2
I still see a lot of `actions/cache@v2` in the code, can we make sure we either change all of them or none of them, just to keep it consistent

2022-05-10 16:08 UTC, zdeveloper commented on .github/workflows/test.yml
> +          name: backtest-report
can we change this to `backend-test-report`, `backtest` is not very descriptive

2022-05-11 21:28 UTC, rin-skylight approved these changes
This looks good to me! Thank you for the hard work on these improvements.

2022-05-11 21:34 UTC, zdeveloper approved these changes
LGTM! thanks for the updates!
All of the jobs look way faster! Except for the `coverity-scan` takes **18 minutes**! I dont see this job on other PRs, is this a new addition?
![image](https://user-images.githubusercontent.com/4952042/167951347-bc45afe9-7f4b-40b2-87c5-77156e60922a.png)

2022-05-11 23:14 UTC, alismx commented
> LGTM! thanks for the updates! All of the jobs look way faster! Except for the `coverity-scan` takes **18 minutes**! I dont see this job on other PRs, is this a new addition? ![image](https://user-images.githubusercontent.com/4952042/167951347-bc45afe9-7f4b-40b2-87c5-77156e60922a.png)

@zdeveloper The `coverity-scan` job usually runs on a cron job but it ran against this PR because I updated the file.

```
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/coverity_scan.yml
 ```

2022-05-11 23:17 UTC, merged