3644/misc fixes
CDCgov/prime-simplereport pull request #3866
Opened 2022-06-07 19:22 UTC by DanielSass

# BACKEND PULL REQUEST

## Related Issue

- #3644 - a few corrections based on feedback from the initial PR

## Changes Proposed

- Moving datahub client configuration values in the application.yaml, adding a description for the new role added

## Additional Information

- previous PR was #3714 

## Testing

- local startup +  unit tests should be sufficient for testing - low impact changes

## Checklist for Primary Reviewer

- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke tested
- [ ] Any content updates (user-facing error messages, etc) have been approved by content team
- [ ] Any changes that might generate questions in the support inbox have been flagged to the support team
- [ ] GraphQL schema changes are backward compatible with older version of the front-end
- [ ] Changes comply with the SimpleReport Style Guide
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

2022-06-07 21:44 UTC, zdeveloper requested changes

2022-06-07 21:44 UTC, zdeveloper commented on backend/src/main/java/gov/cdc/usds/simplereport/config/DataHubClientConfiguration.java
> +  private String simpleReportClientName;
Can we rename this to simpleReportCsvUploadClientName and same for the yaml value? since this will be different from the regular client name for SR

2022-06-07 21:44 UTC, zdeveloper commented on backend/src/main/resources/application-dev.yaml
> +  api-client: "simple_report"
Add new line

2022-06-07 22:52 UTC, emmastephenson approved these changes

2022-06-08 15:41 UTC, emmastephenson submitted a review, later dismissed

2022-06-08 15:43 UTC, zdeveloper requested changes

2022-06-08 15:43 UTC, zdeveloper commented on backend/src/main/resources/application-dev.yaml
> +  api-client: "simple_report"
this also needs to be renamed `csv-upload-api-client`

2022-06-08 19:02 UTC, zdeveloper approved these changes
Thank you!

2022-06-08 19:46 UTC, emmastephenson approved these changes

2022-06-10 19:29 UTC, merged