Encode language change for "Espanol" button
CDCgov/prime-simplereport pull request #4117
Opened 2022-08-01 23:30 UTC by emmastephenson

# FRONTEND PULL REQUEST

## Related Issue

Fixes #3975 
Fixes #4087 
Fixes untracked issue where the overall document language didn't change when a user elected to view the result in Spanish.

## Changes Proposed

- Add a language change to the button specifically (so that the button text "Espanol" is marked Spanish-language)
- Changes the document `lang` attribute to reflect the language chosen in the toggler

## Additional Information

- `document.setAttribute` hack grabbed from the [i18next docs](https://github.com/i18next/react-i18next/issues/925#issuecomment-522299751) but if there's a better way to do this I'm all ears

## Screenshots

https://user-images.githubusercontent.com/80282552/182261908-60ba857d-8f4e-4a9b-8400-7d06b39b42ca.mp4

## Testing

- Validate that document `lang` attribute is correct in all locations

## Checklist for Author and Reviewer

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README

2022-08-02 00:45 UTC, emyl3 submitted a review, later dismissed
This is an edge case and not sure if you want to handle it in this PR but to repro:

On the SimpleReport side I am noticing the wrong language for this scenario:
- go to the "Results" page
- click "Print result" for a test result
- click "Español" in the print modal
- then close the print modal
- everything on the "Results" page will be in English but it will have `<html lang="es">`

2022-08-02 20:21 UTC, nathancrtr commented
> This is an edge case and not sure if you want to handle it in this PR but to repro:
> 
> On the SimpleReport side I am noticing the wrong language for this scenario:
> 
> * go to the "Results" page
> * click "Print result" for a test result
> * click "Español" in the print modal
> * then close the print modal
> * everything on the "Results" page will be in English but it will have `<html lang="es">`

Good catch! This basic issue of "how can we reliably bail out of an i18n-ized state" was never really addressed at its root. In the very first implementation, following your replication steps above and then navigating to the person form would leave the _form itself_ in Spanish! We added [a hook](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/patients/Components/PersonForm.tsx#L115-L121) to the person form to reset the language in such cases, but as we see here more subtle problems still persist.

2022-08-02 20:36 UTC, emmastephenson commented
> 

@nathancrtr and @emyl3 

Interesting, thanks for the additional context Nathan! And good catch Elisa.

What I did to try and get around this was force the document language back to English on modal close. This modal isn't shared directly with patient experience, so I think forcing it back to English on close is appropriate since we don't support Spanish on the internal app. But let me know if you think there's a better implementation!

2022-08-02 22:00 UTC, emyl3 requested changes
Left one comment for the results page. Pxp looked good to me!

2022-08-02 22:35 UTC, emmastephenson commented on frontend/src/app/testResults/TestResultPrintModal.tsx
> +          setDocumentLanguage("en");
Oooh good catch. I moved both calls to the utils file and renamed that function, so now when the language is changed the document language is also automatically changed. Thanks for the through review on this Elisa!!

2022-08-03 13:54 UTC, fzhao99 approved these changes

2022-08-03 14:23 UTC, emyl3 approved these changes
Thank you! LGTM! 😹

2022-08-03 14:44 UTC, merged