Upgrade runtime of azure function.
CDCgov/prime-simplereport pull request #4178
Opened 2022-08-18 21:19 UTC by rin-skylight

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Checklist for Primary Reviewer

- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke tested
- [ ] Any content updates (user-facing error messages, etc) have been approved by content team
- [ ] Any changes that might generate questions in the support inbox have been flagged to the support team
- [ ] GraphQL schema changes are backward compatible with older version of the front-end
- [ ] Changes comply with the SimpleReport Style Guide
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed
- [ ] Any changes to the startup configuration have been documented in the README

----

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Checklist for Primary Reviewer

- [ ] Only database changes are included in this PR
- [ ] Any new tables or columns that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
- [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views (including re-granting permission to the no-PHI user if need be)
- [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] Rollback has been verifed locally and in a deployed environment
- [ ] Any changes to the startup configuration have been documented in the README

----

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?
 
## Checklist for Primary Reviewer

### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README
----

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?
 
## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

## Checklist for Author and Reviewer

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README

2022-08-18 22:17 UTC, rin-skylight commented
@zdeveloper Per our discussion earlier this week, I'm leaving this up to your discretion for when to merge. Please feel free to test at your leisure!

2022-08-19 16:25 UTC, alismx commented
I haven't tested this change, but something of note that I found while browsing the docs:

azurerm_function_app resource has been deprecated in version 3.0 of the AzureRM provider and will be removed in version 4.0. Please use [azurerm_linux_function_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app) and [azurerm_windows_function_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app) resources instead.

2022-08-19 18:05 UTC, rin-skylight commented
@alismx Yep! Azure has done quite a bit in between its provider versions. As a note, the change you're seeing specifically affects the TF provider, not the function itself. We'll have to plan for a larger-scale refactor, as we're back on provider version 2.92.

2022-08-29 16:13 UTC, emmastephenson approved these changes

2022-09-09 16:38 UTC, zdeveloper requested changes
This seems like a change that we wanna deploy on a live env to make sure that azure functions do run as intended on the newer platform.

2022-09-29 17:10 UTC, rin-skylight commented
> This seems like a change that we wanna deploy on a live env to make sure that azure functions do run as intended on the newer platform.

@zdeveloper I agree! That's why I left a merge up to your discretion in my earlier comment, since your team is the set of experts on this. 😄 I was hoping you could give this a test, or assign it to someone who wouldn't mind giving it a whirl.

2022-10-21 18:59 UTC, mehansen commented
@zdeveloper and I paired on this just now, deployed the branch to dev and did a quick smoke test that submitting a result caused the result to get added to the queue and ultimately picked up by the function and submitted to RS. I would love to test the exception handler function as well before we merge
we also ran the [pre-upgrade validator tool](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cwindows%2Cin-process%2Cv4&pivots=programming-language-javascript#run-the-pre-upgrade-validator) and which called out a couple potential issues:
1. potential Function App Name collision - `Function Site Name is over 32 Characters long` Host name (slot host name) gets truncated to 32 characters when generating the host ID so there's potential for collision if it's longer than that. This is only a concern if you have multiple Function Apps ( > 1 including the staging slot) pointing to the same storage account which it appears we do not (@rin-skylight please correct me if I'm wrong) ✅ 
2. `Your Function app has a value set for the AzureWebJobsDashboard app setting, indicating you may be using the Azure WebJobs Dashboard for monitoring function executions. The Azure Functions 3.x runtime logs data to the WebJobs dashboard as a legacy feature; Azure Functions 4.x removes support for the WebJobs dashboard entirely.` This value isn't specified in our terraform anywhere, but it is set for our apps. We removed it from dev without issue.
3. [this issue](https://github.com/Azure/Azure-Functions/issues/2007) was fixed and is a breaking change, but our logic is not dependent on the non-standard data serialization so we are good ✅ 

@rin-skylight before we merge this we probably need to remove the `AzureWebJobsDashboard` app setting from all our function apps. also we noticed this setting and a few others in the function app settings (e.g. `AzureWebJobsStorage`) aren't set in terraform. is that something we can include in our tf code?

2022-10-24 19:07 UTC, mehansen reviewed
tested `ReportStreamExceptionHandler` in `dev` and that looks good as well
this should be good to go once we clean up the deprecated app setting

2022-11-04 22:49 UTC, rin-skylight commented
Following up on this...I can confirm that `AzureWebJobsDashboard` is not controlled by Terraform. It seems that this has proven to be a persistent value in other Azure implementations, to the point that Azure has added it back after deletion. While it should not be a blocker for this upgrade, I have elected to test deletion of this value in `dev`, and will revisit on the 7th to determine whether it has repopulated automatically. (This is true of `AzureWebJobsStorage`, as well.)

2022-11-07 18:08 UTC, rin-skylight commented
The results of the deletion experiment: Azure put the values back by itself. Two teams in the backend are apparently not talking with each other..._thanks, Microsoft._ Confirmation that this isn't just us: https://stackoverflow.com/questions/73726827/azurewebjobsdashboard-no-longer-supported-but-added-automatically-to-azure-func

At this point, there is no fix. (The single answer on that Stack Overflow article that I posted is unrelated to the actual question being asked, so disregard it, please.) Any warnings that `AzureWebJobsDashboard` generates can be safely ignored.

2022-11-10 20:28 UTC, zdeveloper approved these changes

2022-11-14 22:40 UTC, rin-skylight commented
This pull request needs to be closed and re-created due to a check failure. The check cannot be re-run, as it no longer exists.

2022-11-14 22:40 UTC, closed without merging