Bob/4701 conduct tests header
CDCgov/prime-simplereport pull request #4342
Opened 2022-09-29 18:05 UTC by fzhao99

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

2022-10-04 15:02 UTC, BobanL submitted a review, later dismissed

2022-10-04 15:10 UTC, emyl3 requested changes
Saw a couple new accessibility issues with this change!

2022-10-04 15:10 UTC, emyl3 commented on frontend/src/app/testQueue/TestQueue.tsx
> +        <h1 className="font-sans-lg">Conduct tests</h1>
if you add a person to the queue I am seeing the same issue as above: "Heading levels should only increase by one"

2022-10-04 19:29 UTC, emyl3 approved these changes
LGTM! No new accessibility issues seen and the styling looks the same as before. Nice work, Bob!! 🎉

2022-10-04 23:02 UTC, emmastephenson approved these changes
LGTM, thanks for addressing these Bob!

2022-10-05 12:57 UTC, georgehager approved these changes
👍

2022-10-05 13:31 UTC, BobanL approved these changes

2022-10-05 13:53 UTC, merged