Update fhir dependencies in backend. Update Azure Identity in function.
CDCgov/prime-simplereport pull request #5141
Opened 2023-01-26 22:12 UTC by rin-skylight

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

2023-01-26 23:59 UTC, mehansen submitted a review, later dismissed
lgtm! thanks Rin

2023-01-27 13:57 UTC, BobanL requested changes

2023-01-27 13:57 UTC, BobanL commented on backend/build.gradle
> +    implementation 'ca.uhn.hapi.fhir:org.hl7.fhir.utilities:5.6.92' //TODO: Remove when hapi-fhir-structures-r4 is upgraded to invulnerable version. See https://security.snyk.io/vuln/SNYK-JAVA-CAUHNH
Based on this [comment](https://github.com/hapifhir/org.hl7.fhir.core/issues/1082#issuecomment-1400975407), I'm not sure if that latest version is actually sufficient for the fix. I'm sure this one is better than the last one though!

2023-01-27 13:57 UTC, BobanL commented on ops/services/app_functions/report_stream_batched_publisher/functions/package.json
> +    "@azure/identity": "^2.0.0",
Also I ran a depcheck against the function app and it showed that azure/identity is unused in the function app. Even going back to the original commit that added it, I don't believe it was actually ever used. I've tested the function app without it and it works!

2023-02-09 20:42 UTC, BobanL commented
Holding off on upgrading `fhir.utilities` until the security vulnerability has been resolved.

2023-02-10 19:20 UTC, rin-skylight commented
I am going to close and re-create this, as the check-graphql-types check is doing something completely bizarre. It is throwing errors that do not exist on my machine, so I will start fresh.

2023-02-10 19:20 UTC, closed without merging