change form tags in some common components where relevant
CDCgov/prime-simplereport pull request #5312
Opened 2023-02-21 18:08 UTC by fzhao99

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

2023-02-28 14:39 UTC, BobanL submitted a review, later dismissed
Looks good! Thanks :D

2023-02-28 15:02 UTC, emyl3 submitted a review, later dismissed
Checked the various pages via the axe dev tools and it looked good to me! Thank you, Bob!

2023-03-01 18:33 UTC, johanna-skylight requested changes
Overall looks good!. I added a comment on a potential way of setting the form/div element so code is cleaner and with no duplication of html!

2023-03-01 18:33 UTC, johanna-skylight commented on frontend/src/app/commonComponents/RadioGroup.tsx
> +      {renderAsForm ? (
if the only logic changing in this conditional block is the tag then an approach like the one in [this PR](https://github.com/CDCgov/prime-simplereport/pull/5371/files) with the headings would be cleaner

2023-03-02 15:29 UTC, johanna-skylight commented
Because @fzhao99  will be out next week I took the liberty to cleaned up the logic used to set the form or div element in the card and radioGroup component so there is less code duplication. I will need re-reviews to get this PR merge. Thanks!

2023-03-02 15:30 UTC, johanna-skylight approved these changes

2023-03-02 19:33 UTC, emyl3 commented on frontend/src/app/commonComponents/Card/Card.tsx
> +  return <ContainerEl className="card">{body}</ContainerEl>;
once again, this is super neat!! Thanks for refactoring this!

2023-03-02 19:39 UTC, emyl3 approved these changes
Continues to look good! Thank you for refactoring this, @johanna-skylight, and for all your work on this @fzhao99!! 😸

2023-03-06 14:37 UTC, fzhao99 commented
@johanna-skylight thanks for the fix Johanna! Was looking for something exactly like that but didn't know that you could work with strings // JSX like that. Archiving for later 😊

2023-03-06 14:37 UTC, merged