Add page titles to test results bulk upload
CDCgov/prime-simplereport pull request #5336
Opened 2023-02-24 22:45 UTC by emyl3

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

2023-03-01 14:23 UTC, johanna-skylight requested changes

2023-03-01 16:59 UTC, emyl3 commented on frontend/src/app/testResults/uploads/CsvSchemaDocumentation.tsx
> +  });
ooo got it! Thank you!

2023-03-01 19:24 UTC, emyl3 commented
@johanna-skylight Please don't re-reivew yet haha sorry!!! Just checking one thing beforehand ^__^"

2023-03-01 19:29 UTC, johanna-skylight commented
> @johanna-skylight Please don't re-reivew yet haha sorry!!! Just checking one thing beforehand ^__^"

I was about to point out that I think the best way to check the location is not to use the href in the window object but to ask react router for it https://reactrouter.com/en/main/hooks/use-location

2023-03-01 21:07 UTC, emyl3 commented
@johanna-skylight ready for re-review!

2023-03-01 21:40 UTC, johanna-skylight commented on frontend/src/app/testResults/uploads/CsvSchemaDocumentation.tsx
> +  }, [location, pageTitle]);
Yeah, this alert should be dismissed ad the location is retrieved from the react router library and all the values returned from getPageTitle are hardcoded in the function

2023-03-01 21:41 UTC, johanna-skylight approved these changes
LGTM! thanks for the work on this tricky ticket 💯

2023-03-02 16:38 UTC, BobanL approved these changes
Looks good! 😃

2023-03-02 16:59 UTC, merged