Make shared bulk upload values consistent
CDCgov/prime-simplereport pull request #5509
Opened 2023-03-23 02:11 UTC by emyl3

# BACKEND & FRONTEND PULL REQUEST

## Related Issue
- partially resolves #5456 
- #5456 also involves static site changes which will be made separately

## Changes Proposed
- This PR makes shared bulk upload values (across the test results bulk upload and patient bulk upload) like race, ethnicity, gender, employed in healthcare, and resident congregate setting accept the same values across both uploaders.

## Additional Information

## Testing

- How should reviewers verify this PR?

2023-03-24 14:14 UTC, emyl3 commented on backend/src/test/java/gov/cdc/usds/simplereport/service/PatientBulkUploadServiceAsyncTest.java
> +  @SliceTestConfiguration.WithSimpleReportOtherOrgUser
⚠️ This test kept failing with the addition of the new test above. The StandardUser in this configuration had the same email as the StandardAllFacilitiesUser so something weird was happening here. Just decided to make a new user in a different org to test this scenario.

2023-03-27 14:17 UTC, BobanL commented on frontend/src/app/testResults/uploads/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
> -                      Ask, but unknown
When I attempt to upload a file to Results uploader with `Ask but unknown` I get an error from Report Stream's validation. I believe (based on my CSV editor) that if you have a comma in a field you can just put the value in quotes and it seems to work like this `"Ask, but unknown"`.

2023-03-27 15:08 UTC, BobanL requested changes
It seems like "Unknown" codes don't map well back onto the UI when viewing the patients again. For both Ethnicity & Race the fields don't show up.

2023-03-27 15:08 UTC, BobanL commented on backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java
> +            Map.entry(UNKNOWN_CODE, UNKNOWN_LITERAL));
When I upload a [patient](https://dev2.simplereport.gov/app/patient/3c51c6d6-083d-4526-9080-bac45becef40?facility=1a0139b9-fc23-450b-9b6c-cd081e5cea9d) with "UNK" or "unknown", their race fields are missing when I look at it again. 
![image](https://user-images.githubusercontent.com/10108172/227981174-5760e2ca-5e67-4be1-87aa-0c2045c5545a.png)

2023-03-27 15:08 UTC, BobanL commented on backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java
>              Map.entry(UNKNOWN_LITERAL, UNKNOWN_LITERAL));
Similar to Race, but when I upload a [patient](https://dev2.simplereport.gov/app/patient/e4476dbd-0191-48d3-8849-5d036ac3eeb3?facility=1a0139b9-fc23-450b-9b6c-cd081e5cea9d) with "UNK" or "UNKOWN" ethnicity that section is empty. 
![image](https://user-images.githubusercontent.com/10108172/227981931-cad31a41-4e0c-4d7e-a76b-424898160396.png)

2023-03-27 15:17 UTC, emyl3 commented
> It seems like "Unknown" codes don't map well back onto the UI when viewing the patients again. For both Ethnicity & Race the fields don't show up.

Hmmm, so I was saving those as "unknown" in the database. I'm wondering if it makes sense to save the value for Race and Ethnicity "unknown" values to "refused" in the database like the gender field so they get marked as "Prefer not to answer" in the UI? 🤔

2023-03-27 16:15 UTC, BobanL commented on frontend/src/app/testResults/uploads/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
> -                      Ask, but unknown
This error comes from Report Stream, but if you look at [HL7 docs](https://hl7-definition.caristix.com/v2/HL7v2.7/Tables/0005) it shows asku isn't even valid for race 🤔

2023-03-27 16:19 UTC, emyl3 commented on frontend/src/app/testResults/uploads/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
> -                      Ask, but unknown
OOO... I'll check-in with the rest of the team to see what this value was used for beforehand then 👀 Thank you for flagging that 😅

2023-03-27 18:08 UTC, emyl3 commented
> > It seems like "Unknown" codes don't map well back onto the UI when viewing the patients again. For both Ethnicity & Race the fields don't show up.
> 
> Hmmm, so I was saving those as "unknown" in the database. I'm wondering if it makes sense to save the value for Race and Ethnicity "unknown" values to "refused" in the database like the gender field so they get marked as "Prefer not to answer" in the UI? 🤔

From standup, it was decided to set these as "refused" so they display as "Prefer not to answer" in the UI

2023-03-27 19:03 UTC, emyl3 commented on frontend/src/app/testResults/uploads/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
> -                      Ask, but unknown
Changed it back to "Ask, but unknown" ReportStream lists it [as supported here](https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v3.0.pdf) but it throws an error when trying to submit that value. So @BobanL [flagged the issue here](https://skylight-hq.slack.com/archives/C01HFHPNJEL/p1679939568399459?thread_ts=1679927969.588359&cid=C01HFHPNJEL).

2023-03-27 19:03 UTC, emyl3 commented on frontend/src/app/testResults/uploads/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
> -                      Ask, but unknown
Will also need to update patient bulk upload guide PR for static site

2023-03-27 20:33 UTC, emyl3 commented
@BobanL ready for re-review! Thank you!!

2023-03-28 12:02 UTC, BobanL approved these changes
Changes look good to me! Thank you!!

2023-03-28 13:12 UTC, johanna-skylight approved these changes
LGTM!

2023-03-28 14:33 UTC, merged