refactor new user form to use react hook form
CDCgov/prime-simplereport pull request #5949
Opened 2023-06-08 20:54 UTC by BobanL

# BACKEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DATABASE PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# DEVOPS PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

---

# FRONTEND PULL REQUEST

## Related Issue

- Why is this being done? Link to issue, or a few sentences describing why this PR exists

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

2023-06-22 15:04 UTC, fzhao99 commented on frontend/src/app/Settings/Users/UserFacilitiesSettings.tsx
> +    if (value === "ALL_FACILITIES") {
nit: could we un-nest these logical checks and just put them all in the top row?

2023-06-22 16:37 UTC, emyl3 requested changes
One edge case I noticed,
- get in a state where the "At least one facility must be selected" error appears
- then select "Access Level" to be "Admin"
- it will check all the facilities and disable the facility selection but the error remains
<img width="663" alt="Screenshot 2023-06-22 at 11 34 26" src="https://github.com/CDCgov/prime-simplereport/assets/20211771/39e8ad43-074e-417e-80be-6914f210f0c6">

2023-06-22 22:25 UTC, emyl3 approved these changes
LGTM! Tested on dev! Thank you, Boban!

2023-06-23 13:20 UTC, fzhao99 approved these changes

2023-06-23 16:04 UTC, johanna-skylight approved these changes
🚀

2023-06-23 16:05 UTC, merged